global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'autobot-production'
    replica: '1'

# Alertmanager configuration (optional)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#           - alertmanager:9093

# Load rules once and periodically evaluate them
# rule_files:
#   - "alerts/*.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Back Office Server
  - job_name: 'back_office_server'
    static_configs:
      - targets: ['back_office_server:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # PostgreSQL exporter (if installed)
  # - job_name: 'postgres'
  #   static_configs:
  #     - targets: ['postgres-exporter:9187']

  # Redis exporter (if installed)
  # - job_name: 'redis'
  #   static_configs:
  #     - targets: ['redis-exporter:9121']

  # Node exporter (if installed)
  # - job_name: 'node'
  #   static_configs:
  #     - targets: ['node-exporter:9100']

  # Docker metrics (if Docker metrics enabled)
  # - job_name: 'docker'
  #   static_configs:
  #     - targets: ['host.docker.internal:9323']
